#!/bin/bash -i

shopt -s expand_aliases

alias sail='[ -f sail ] && bash sail || bash vendor/bin/sail'
(
    this="create-sail-app"

    if [ -z "$1" ]
        then
            read -p 'Project name: (default: "new-project-#") ' projectname
        else
            projectname=$1
    fi

    # handle empty input
    if [ -z "$projectname" ]
        then
            projectname="new-project-0"
    fi

    cd ..
    while [ -d "$projectname" ]
        do
            size=${#projectname}
            count=$((${projectname:(-1)} + 1))
            projectname="${projectname:0:($size-1)}${count}"
    done
    echo "Creating ${projectname} at "
    pwd


    #Open Docker, only if is not running
    if (! docker stats --no-stream ); then
        # On Mac OS this would be the terminal command to launch Docker
        open /Applications/Docker.app
        #Wait until Docker daemon is running and has completed initialisation
        while (! docker stats --no-stream ); do
            # Docker takes a few seconds to initialize
            echo "Waiting for Docker Daemon to launch... (this can take a minute)"
            sleep 9
        done
    fi  

    echo "Docker running!"

    # install laravel & sail
    # currently unused sail packages: memcached,minio
    if open -a Docker ; then
        curl -s "https://laravel.build/${projectname}?with=pgsql,redis,meilisearch,selenium,mailhog" | bash
    else
        exit "Docker did not open; please open Docker Desktop and try again."
    fi

    # set up environment
    cd $projectname

    echo "launching environment at"
    pwd

    sail up -d

    # install jetstream
    sail composer require laravel/jetstream
    sail artisan jetstream:install inertia --ssr

    # database tools
    sail composer require doctrine/dbal
    sail composer require jzonta/faker-restaurant

    # user permissions
    sail composer require spatie/laravel-permission

    sail composer install

    # prepare frontend
    sail npm install
    sail npm install -D vitest
    sail npm install @vueuse/core
    sail npm install eslint
    sail npm install eslint-config-google
    sail npm install eslint-plugin-editorconfig
    sail npm install eslint-plugin-tailwindcss
    sail npm install eslint-plugin-vue
    sail npm install eslint-plugin-yml
    sail npm run build

    # rebuild container
    sail build

    # database migrations
    sail artisan migrate

    # laravel services
    sail artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider"

    # copy config files
    cp ../$this/.config/.eslintignore ../$projectname
    cp ../$this/.config/.eslintrc.js ../$projectname
    cp ../$this/.config/.zshrc ../$projectname    

    # copy Hello World
    cp ../$this/.js/Components/Welcome.vue ./resources/js/Components/
    cp ../$this/.js/Pages/Welcome.vue ./resources/js/Pages/

    code ./
    code ./resources/js/Components/Welcome.vue

    open http://${projectname}.test

    # serve frontend
    sail npm run dev
)